# Generated by Django 5.2.3 on 2025-06-23 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusId',
            fields=[
                ('bonus_id', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'Генерация бонусных карточек',
                'verbose_name_plural': 'Генерация бонусных карточек',
            },
        ),
        migrations.CreateModel(
            name='BonusCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('bonus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.bonusid', verbose_name='Уникальный номер карты')),
            ],
            options={
                'verbose_name': 'Список/База карточек',
                'verbose_name_plural': 'Список/База карточек',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='bonus_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_bonus', to='users.bonuscard'),
        ),
    ]
