# Generated by Django 5.2.1 on 2025-06-26 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_bonusid_bonuscard_alter_user_bonus_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bonuscard',
            options={'verbose_name': 'Список/База карточек', 'verbose_name_plural': 'Список/База карточек'},
        ),
        migrations.AlterModelOptions(
            name='bonusid',
            options={'verbose_name': 'Генерация бонусных карточек', 'verbose_name_plural': 'Генерация бонусных карточек'},
        ),
    ]
