# Generated by Django 5.2.3 on 2025-07-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_cardloginattempt_user_external_id_1c_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonuscard',
            name='address',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='bonuscard',
            name='first_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='bonuscard',
            name='last_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='bonuscard',
            name='phone',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
