# Generated by Django 5.2.3 on 2025-07-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_date_joined_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='bpsyx@MN51', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
