# Generated by Django 5.2.3 on 2025-07-11 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_cardloginattempt_user_external_id_1c_and_more'),
        ('users', '0006_alter_user_password'),
    ]

    operations = [
    ]
