# Generated by Django 5.2.3 on 2025-07-17 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_merge_20250711_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonuscard',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='bonuscard',
            name='address',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='bonuscard',
            name='first_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='bonuscard',
            name='last_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='bonuscard',
            name='phone',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Номер телефона'),
        ),
    ]
