# Generated by Django 5.2.3 on 2025-07-17 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_bonuscard_bonus_id_alter_user_bonus_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonuscard',
            name='bonus_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.bonusid', verbose_name='Уникальный номер карты'),
        ),
    ]
