# Generated by Django 5.2.1 on 2025-05-31 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0004_storebranch'),
        ('products', '0008_product_bonus_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasesHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('bonus_count', models.IntegerField(default=0)),
                ('total_price', models.IntegerField(default=0)),
                ('price_for', models.CharField(choices=[('кг.', 'кг.'), ('шт.', 'шт.'), ('литр', 'литр'), ('метр', 'метр')], default='шт', editable=False, max_length=500, verbose_name='Цена за')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.storebranch')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Товар')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
