# Generated by Django 5.2.1 on 2025-05-29 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('img', models.ImageField(upload_to='product/category/%Y_%m', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Категорию',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonusAccrual', models.BooleanField(default=True, verbose_name='Зачисляется бонус')),
                ('is_on_sale', models.BooleanField(default=True, verbose_name='Наличие товара')),
                ('is_promotion', models.BooleanField(default=False, verbose_name='Товар находится в акции')),
                ('title', models.CharField(max_length=300, verbose_name='Название товара')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание товара')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('old_price', models.CharField(blank=True, max_length=100, null=True, verbose_name='Старая цена')),
                ('code', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Артикул')),
                ('brand', models.CharField(blank=True, null=True, verbose_name='Название брэнда')),
                ('country_production', models.CharField(verbose_name='Страна производства')),
                ('weight', models.CharField(blank=True, null=True, verbose_name='Вес')),
                ('expiration_date', models.CharField(blank=True, null=True, verbose_name='Срок годности')),
                ('nutritional_value', models.CharField(blank=True, null=True, verbose_name='Пищевая ценность')),
                ('price_for', models.CharField(choices=[('кг.', 'кг.'), ('шт.', 'шт.'), ('литр', 'литр'), ('метр', 'метр')], default='шт', editable=False, max_length=500, verbose_name='Цена за')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата последнего изменения')),
                ('from_wh', models.BooleanField(default=False, editable=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товара',
                'verbose_name_plural': 'Товар',
                'ordering': ['-id'],
            },
        ),
    ]
