# Generated by Django 5.2.1 on 2025-05-30 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_storebranch'),
        ('products', '0003_alter_productimage_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='branches',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.storebranch', verbose_name='Филиал'),
            preserve_default=False,
        ),
    ]
