# Generated by Django 5.2.1 on 2025-05-30 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_is_new_product_is_popular'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='branches',
            new_name='location',
        ),
    ]
