# Generated by Django 5.2.1 on 2025-05-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_rename_branches_product_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bonus_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Кл-во бонусов при покупке товара'),
        ),
    ]
