# Generated by Django 5.2.1 on 2025-06-08 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_price_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='best_product',
            field=models.BooleanField(default=False, verbose_name='Хит продаж'),
        ),
    ]
