# Generated by Django 5.2.1 on 2025-06-11 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_description_faq_answer_and_more'),
        ('products', '0010_product_best_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.storebranch', verbose_name='Филиал'),
        ),
    ]
