# Generated by Django 5.2.1 on 2025-05-27 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('img', models.ImageField(upload_to='story_images', verbose_name='Изображение')),
                ('link', models.URLField(blank=True, help_text='Если есть', max_length=500, null=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'История',
                'verbose_name_plural': 'Истории',
            },
        ),
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_token', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sendtoall', models.BooleanField(default=True, verbose_name='Отправить всем')),
                ('title', models.CharField(max_length=255, verbose_name='Уведомление')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('big_img', models.ImageField(blank=True, help_text='Большое фото товара для магазина, обложка новости, рекламный баннер или иллюстрация к событию.', null=True, upload_to='notifications/%Y_%m', verbose_name='Оболожка')),
                ('large_img', models.ImageField(blank=True, help_text='Тематическая иконка, связанная с содержимым уведомления (например, значок акции или события).', null=True, upload_to='notifications/%Y_%m', verbose_name='Значок акции')),
                ('user_id', models.ManyToManyField(blank=True, help_text='**Если хотите уведомить всех, оставьте это поле пустым**', to='main.devicetoken', verbose_name='Кому отправить?')),
            ],
            options={
                'verbose_name': 'Уведомления',
                'verbose_name_plural': 'Уведомлении',
            },
        ),
        migrations.CreateModel(
            name='StoryVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.FileField(upload_to='stories', verbose_name='История')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='main.stories')),
            ],
            options={
                'verbose_name': 'История',
                'verbose_name_plural': 'Истории',
            },
        ),
    ]
