# Generated by Django 5.2.1 on 2025-05-27 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stories',
            name='title',
            field=models.CharField(default='wefwef', max_length=255, verbose_name='Заголовок истории'),
            preserve_default=False,
        ),
    ]
