# Generated by Django 5.2.1 on 2025-06-10 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_faq'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faq',
            old_name='description',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='title',
            new_name='question',
        ),
    ]
